### PR TITLE
remove automerge

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @xylar

### CODE REVIEW

**Comment by ocefpaf** [comment]
I added the automerge button in a remove automerge PR. Oh the irony!!

**Comment by xylar** [comment]
Fair enough!  Thanks for doing this!

**Comment by xylar** [comment]
Also ironically, the bot seems to be ignoring your auto-merge request.

**Comment by ocefpaf** [comment]
> Also ironically, the bot seems to be ignoring your auto-merge request.

I smell a bot uprising!

**Pull request merged**
