### PR TITLE
Add bash activate scripts to windows

### PR DESCRIPTION
**Pull request by xylar**
Needed for windows bash

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Addresses #56 for newer proj version.

**Comment by xylar** [comment]
@ocefpaf, if you want to take a look at this one along with #57, that'd be great!

**Comment by ocefpaf** [comment]
:tada:

**Pull request merged**
