### PR TITLE
Fix activate script for Windows bash in v5.2.0

### LINKED ISSUE #59: PROJ_LIB not set in Windows bash or powershell
I noticed some strange behavior with pyproj 1.9.6 using PROJ 5.2.0 on Windows and tracked it down to a problem with the activate scripts for bash and powershell (if meant to be supported). This doesn't seem to be a problem for newer versions of PROJ (greater than 5.2.0), but since not all of my dependencies were with newer versions of PROJ I'm a little stuck. I'm guessing PROJ >5.2 does a better job finding the PROJ directory? Or maybe there is a patch in the build to point it to the right place?

A simple python example:

```
conda create -y -n test python=3.7 pyproj rasterio cartopy gdal
conda activate test
from pyproj import Proj; pj = Proj({'proj': 'eqc', 'lon_0': 0.0, 'lat_0': 0.0})"
```

This will produce:

```
(test) PS C:\Users\User> python -c "from pyproj import Proj; pj = Proj({'proj': 'eqc', 'lon_0': 0.0, 'lat_0': 0.0})"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\Miniconda3\envs\test\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'major axis or radius = 0 or not given'
```

If you then set PROJ_LIB, it works fine. Powershell example:

```
Set-Item Env:PROJ_LIB "C:\Users\User\Miniconda3\envs\test\Library\share"
```

This is also happening for me on Travis CI for one of my projects where travis defaults to using git bash for Windows execution. I think the easiest fix may be to change the last `elif` of the `activate.sh` to an `else` [here](https://github.com/conda-forge/proj.4-feedstock/blob/master/recipe/scripts/activate.sh#L13) but it would have to be backported to PROJ 5.2.0 to fix the issue I'm seeing.

I'm not an expert on PROJ or Windows so let me know what doesn't make sense and what is unreasonable.

<br/>
Environment (<code>conda list proj</code>):
<details>

```
$ conda list proj
# packages in environment at C:\Users\User\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
proj4                     5.2.0             h6538335_1005    conda-forge
pyproj                    1.9.6           py37hfa6e2cd_1002    conda-forge
```
</details>

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #59

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by djhoese** [comment]
Awesome! Thanks for this. Once this is merged and available I'll try rerunning my failing travis Windows job.

**Comment by xylar** [comment]
Yep, give it at least an hour -- it takes awhile for the databases to update, as you may know.  You can watch for the files here:
https://anaconda.org/conda-forge/proj4/files
But even after they show up, it can take some time before a conda install will see them.

**Comment by ocefpaf** [comment]
Thanks for fixing this!

**Pull request merged**
