### PR TITLE
hide batch command execution

### PR DESCRIPTION
**Pull request by scw**
Currently, on deactivating an environment, this script outputs each step its executing. Hide these executions.

### CODE REVIEW

**Comment by ocefpaf** [comment]
LGTM can you re-render (http://conda-forge.github.io/docs/conda_smithy.html) to fix the Windows issue, and bump the build number to create a new package so this change makes into the channel?

Let me know if you have any doubt on how to do that.

**Comment by scw** [comment]
@ocefpaf Thanks for the pointers. I rerendered and bumped the build number, let me know if this needs anything else.

**Comment by ocefpaf** [comment]
>  let me know if this needs anything else.

Nope. Everything looks good. Just waiting one the CIs to merge this. Thanks for the PR!

**Comment by scw** [comment]
Looks like there was a dependency on curl that wasn't explicitly included in the recipe. I've added that, which fixes the shift grid checks locally, and should also work on the Windows CI build.

**Comment by ocefpaf** [comment]
curl was available in AppVeyor by default (I guess it is still available
but not in the path) specifying as a build dependency is the right thing to
do. Thanks.

On Mar 24, 2017 8:24 PM, "Shaun Walbridge" <notifications@github.com> wrote:

Looks like there was a dependency on curl that wasn't explicitly included
in the recipe. I've added that, which fixes the shift grid checks locally,
and should also work on the Windows CI build.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/proj.4-feedstock/pull/21#issuecomment-289166284>,
or mute the thread

**Pull request merged**
