### PR TITLE
Rebuild 5.2.0 with azure only, add activate.sh for windows bash

### LINKED ISSUE #56: EPSG codes no longer work on Windows
Issue: I'm currently helping debug some stuff with [ci-helpers](https://github.com/astropy/ci-helpers) and I finally got a Windows environment on travis to run my unit tests for pyresample. However, there are some tests failing that weren't failing on linux/osx earlier this morning (rerunning them now). I'm trying to track down what may have changed and hoping the people who deal with this feedstock will be the quickest solution. @snowman2 and @ocefpaf seems you've been dealing with the newer versions of PROJ, but this environment is still using the older 5.4.0. Here's what is installed:

```
    proj4-5.2.0                |    h6538335_1004         3.4 MB  conda-forge
    pyproj-1.9.6               |py36hfa6e2cd_1002         237 KB  conda-forge
```

When I do `Proj("+init=EPSG:6932")` with pyproj I get:

```
  File "c:\users\travis\build\pytroll\pyresample\pyresample\geometry.py", line 1041, in __init__
    proj = Proj(projection)
  File "C:\tools\miniconda3\envs\test\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'no arguments in initialization list'
```

My guess is that either PROJ or this feedstock changed the default to no longer the `+init` syntax (since I know it is being deprecated), but I'm having trouble tracking down where that happened. Any ideas?

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #56

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@ocefpaf, I know you get added automatically as a reviewer but it would be good if you took a look before I merge (assuming CI passes correctly).  I followed some of the changes you made in #55 but obviously we don't want to change the package name.  I'd like to know if what I did here seems okay to you, and if it should fix #56 as I suspect.

**Comment by xylar** [comment]
Walking back the windows build changes...

**Comment by xylar** [comment]
Hmm, I no longer think this PR will help with #56.  It seems like the problem is with expecting `proj4-activate.sh` when only `proj4-activate.bat` is available in the windows build.

Update: this PR should address the issue by adding the .sh script, following the same approach used in the gdal feedstock: https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/install_lib.bat#L25-L30

**Comment by ocefpaf** [comment]
Awesome! Thanks!!

**Pull request merged**
