### PR TITLE
Rerender v7.0.1

### LINKED ISSUE #84: v7.0.1 does not appear to be on anaconda.org
I can see that the recipe currently specifies v7.0.1, but there are no corresponding files on anaconda.org:

https://anaconda.org/conda-forge/proj/files

### PR DESCRIPTION
**Pull request by xylar**
closes #84 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
CI doesn't seem to have uploaded the results of #81 so I'm trying again.  Not bumping the build number because the last one never happened...

**Comment by xylar** [comment]
Before I merge this, I want to make sure there isn't some reason that 7.0.1 was removed.  https://github.com/conda-forge/proj.4-feedstock/pull/83#issuecomment-629361963 seems to imply that there were some issues?

**Comment by xylar** [comment]
https://github.com/conda-forge/proj.4-feedstock/pull/83#issuecomment-631462941: 

@hobu, you're good with this being merged, then?

**Comment by hobu** [comment]
> @hobu, you're good with this being merged, then?

You bet, merge away.

**Comment by ocefpaf** [comment]
We will wait for the new release to update the `pin` though, right?

**Comment by hobu** [comment]
7.0.1 is the new release. I have cleared it of the performance issue, and we are ready to adjust the pin whenever you need.

**Comment by ocefpaf** [comment]
> 7.0.1 is the new release. I have cleared it of the performance issue, and we are ready to adjust the pin whenever you need.

Sorry! I missed that! Let's re-pin then!

**Pull request merged**
