### PR TITLE
Do not skip ppc, needed for e.g. vtk

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Needed for https://github.com/conda-forge/vtk-feedstock/pull/335

**Comment by Tobias-Fischer** [comment]
This is ready for review @conda-forge/proj-4

**Comment by xylar** [comment]
@Tobias-Fischer, we had silenced an error for ppc64le in #141.  This led to downstream problems.  I attempted to debug this issue in #142 without success, so we disabled ppc64le support in #143 (but neglected to remove the code that skipped one of the tests for ppc64le).  I have unsilenced the test here, as I did in #142.  I expect the same outcome as there, namely that the test produces different results the first and second time it is run on ppc64le.  If the issue has gone away on its own, that will be wonderful but otherwise, someone still needs to investigate it further and find a fix.  None of the maintainers here want to sink any more time into it.

**Comment by Tobias-Fischer** [comment]
Thanks a lot for the explanation, I now recall seeing this issue before. I’m not planning to spend time on it either, so have proposed to skip ppc64 in vtk as well.

**Comment by xylar** [comment]
@Tobias-Fischer, I think that's the easier fix for now.  It's unfortunate to be dropping ppc64le so many places but it's also just not a fun problem to figure out...

**Comment by mfansler** [comment]
@xylar would you mind creating an Issue here to document the ppc64le skip and maybe pinning it? It would be useful to have canonical reference for why we're skipping ppc64le on downstream feedstocks.

The content in https://github.com/conda-forge/proj.4-feedstock/pull/147#issuecomment-2232505591 is already excellent documentation!

**Comment by xylar** [comment]
Good call, done in https://github.com/conda-forge/proj.4-feedstock/issues/148

**Pull request closed without merging**
