### PR TITLE
remove bash-specific syntax in activate scripts

### LINKED ISSUE #67: Make activate.sh posix compliant
I think [recipe/scripts/activate.sh](https://github.com/conda-forge/proj.4-feedstock/blob/master/recipe/scripts/activate.sh) is being source and not executed by conda scripts, so the `#!/bin/bash` is ignored.
If conda is run from /bin/sh as it is the case in CI environments or docker builds, then bash syntax extensions cause issues.

Coud you please use the standard test syntax `if [ -n "$PROJ_LIB" ]; then` instead of `if [[ -n "$PROJ_LIB" ]]; then`?

### PR DESCRIPTION
**Pull request by nlgranger**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes: #67

### CODE REVIEW

**Comment by nlgranger** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Can you bump the build number in the meta.yaml so it produces a new package?

**Comment by nlgranger** [comment]
Just FYI: I bumped the build number in the latest commit and push-forced it. Does it need some extra manual testing or can we rely on the CI tests?

**Comment by xylar** [comment]
I think CI is sufficient. If you find it doesn't do what you expected, it can be fixed (once again) later

**Comment by xylar** [comment]
However, I'm still not seeing any change in the build number. Could you double check that it got bumped and committed?

**Comment by nlgranger** [comment]
My bad, it is fixed now.

**Pull request merged**
