### PR TITLE
rebuild PROJ 8.1.1 with updated sqlite build

### PR DESCRIPTION
**Pull request by snowman2**
Related:
- https://github.com/conda-forge/sqlite-feedstock/pull/68
- https://github.com/conda-forge/proj.4-feedstock/issues/112

### CODE REVIEW

**Comment by snowman2** [comment]
@ocefpaf is there something that needs to be done to build with the `_1` tag of sqlite?
I currently see `_0`:
```
sqlite                    3.36.0               h9cd32fc_0 
```

**Comment by xylar** [comment]
@conda-forge admin, please restart ci

**Comment by xylar** [comment]
@snowman2, for which platform are you still seeing the `_0` tag?  I looked at `linux64` and the tag was `_1` as expected.  It looks like `linux-aarch64` just built about 7 hours ago (https://anaconda.org/conda-forge/sqlite/files) so maybe that one wasn't available yet for your last build?  Let's try one more time.

**Comment by xylar** [comment]
@conda-forge-admin, please restart ci

**Comment by xylar** [comment]
@snowman2, as far as I can tell the sqlite build is now `_1`.  Let me know if you see any builds where that's not the case.

**Comment by snowman2** [comment]
Looks good, thanks @xylar 👍

**Pull request merged**
