### PR TITLE
Fix fish-incompatible syntax in activate.fish

### PR DESCRIPTION
**Pull request by sjpfenninger**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@sjpfenninger, thanks for this help.  I'm not very good at `fish` and am probably responsible for these mistakes.

**Comment by sjpfenninger** [comment]
@xylar No worries, and thanks for the rapid processing!

**Comment by hobu** [comment]
This reminds me that I think the `hub` recipe needs the same.

**Pull request merged**
