### PR TITLE
Re-enable ppc64le

### LINKED ISSUE #148: Why we are skipping `ppc64le`
We have been forced to skip `ppc64le` on this feedstock, resulting on any downstream feedstocks that depend on `proj` having to do the same.  This is the story of why.

We had silenced an error for ppc64le in https://github.com/conda-forge/proj.4-feedstock/pull/141. This led to downstream problems. I attempted to debug this issue in https://github.com/conda-forge/proj.4-feedstock/pull/142 without success, so we disabled ppc64le support in https://github.com/conda-forge/proj.4-feedstock/pull/143 (but neglected to remove the code that skipped one of the tests for ppc64le). I have unsilenced the test in #142 and again in #147. In both cases, the test produces different results the first and second time it is run on ppc64le. None of the maintainers here want to sink any more time into it.

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #148

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I was able to successfully test @mwtoews' approach in https://github.com/conda-forge/pyproj-feedstock/pull/152 with the test build from #149.  Since we don't (at least so far) know of any problems with `ppc64le` "in the wild", I think it's time to re-enable it and see how it goes.

**Comment by xylar** [comment]
@snowman2, @mwtoews, @hobu, @ocefpaf, any objections with me proceeding with this?  I'll do my best to re-enable ppc64le where it's been disabled because of `proj`.

**Comment by hobu** [comment]
> any objections with me proceeding with this?

Fine with me. The entire episode made me wonder if architecture pins were such a thing? It would seem would should have been able to shut off ppc64le from just the PROJ recipe and the rest of the dependencies would have cascaded without modification when they were rerendered. Am I misunderstanding how things could/should/do work?

**Comment by xylar** [comment]
> It would seem would should have been able to shut off ppc64le from just the PROJ recipe and the rest of the dependencies would have cascaded without modification when they were rerendered. Am I misunderstanding how things could/should/do work?

No, unfortunately, that isn't how it works.  While enabling of advanced architectures only happens if the packages from upstream feedstocks are already available, the same is not true of disabling them.  Instead, each feedstock has to notice that ppc64le is failing, find out why (no `proj` package in this case), find out if that's on purpose (yes in this case) and then disable ppc64le themselves.  Likewise, reenabling ppc64le will be a (perhaps painful) manual process.

**Comment by ocefpaf** [comment]
We never had a case like this one before. While we could implement something in the bot I wonder how many other similar cases we will have to make it worth the effort.

**Comment by xylar** [comment]
I also think it's too specific to worry about having the bot handle such a case.

**Comment by xylar** [comment]
I'll proceed tomorrow morning (European time) if I haven't heard any objections.

**Pull request merged**
